# Gait Params for moonwalk

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  0.00, -0.00, 0.0,  0.00, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  -0.065, -0.00, 0.0,  -0.065, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 240

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.00, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  0.00, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [-0.065, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  -0.065, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 240

# 2
[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  0.00, -0.00, 0.0,  0.00, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  -0.065, -0.00, 0.0,  -0.065, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 240

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.00, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  0.00, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [-0.065, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  -0.065, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 240

# 3
[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  0.00, -0.00, 0.0,  0.00, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  -0.065, -0.00, 0.0,  -0.065, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 240

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.00, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  0.00, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [-0.065, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  -0.065, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 240

# 4
[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  0.00, -0.00, 0.0,  0.00, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  -0.065, -0.00, 0.0,  -0.065, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 240

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.00, 0.00, 0.0,  0.00, -0.00, 0.0,  0.00, 0.00, 0.0,  0.00, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [-0.00, 0.00, 0.0,  0.00, -0.00, 0.0,  0.00, 0.00, 0.0,  -0.00, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 110
duration        = 240

# End of moonwalk #
